
POST http://localhost:3000/get-blog
Content-Type: application/json

{
  "blog_id": "Tast-reactfDU-RypJrr9raLXA7Fhtq"
}



# POST http://localhost:3000/get-profile
# Content-Type: application/json

# {
#   "username": "sunitsen50"
# }